# Generated by Django 4.1.5 on 2023-01-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='img',
        ),
        migrations.AddField(
            model_name='polish',
            name='image',
            field=models.CharField(default='https://www.dictionary.com/e/wp-content/uploads/2018/02/nail-polish-light-skin-tone.png', max_length=400),
        ),
    ]
