# Generated by Django 4.1.6 on 2023-02-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
